# 使用官方的 Miniconda 基础镜像
FROM continuumio/miniconda3

# 更新包管理器并安装必要的系统依赖
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 创建并激活新的 Conda 环境
RUN conda create -n llamaindex python=3.10 && \
    echo "conda activate llamaindex" >> ~/.bashrc

# 安装 LlamaIndex 及其相关依赖
RUN /bin/bash -c "source ~/.bashrc && \
    conda activate llamaindex && \
    pip install llama-index && \
    pip install llama-index-llms-ollama && \
    pip install llama_index.tools && \
    pip install llama-index-embeddings-huggingface"

# # 安装 PyTorch（根据您的 CUDA 版本选择合适的版本）
# RUN /bin/bash -c "source ~/.bashrc && \
#     conda activate llamaindex && \
#     pip install torch==2.5.0 torchvision==0.20.0 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cu121"

# 创建工作目录
RUN mkdir /app
WORKDIR /app

# 设置环境变量以防止 Python 生成 .pyc 文件
ENV PYTHONDONTWRITEBYTECODE=1

# 设置默认命令以保持容器运行
CMD ["/bin/bash"]