x-default-opts: &default-opts
  restart: always
  tty: true
  stdin_open: true
  privileged: false
  ipc: private

services:
  llamaindex:
    <<: *default-opts
    image: tsukisama9292/server:llamaindex-rolling
    container_name: llamaindex
    ports:
      - "40080:80"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    volumes:
      - .:/app