FROM continuumio/miniconda3

# 初始化 Conda
RUN conda init

# 創建新的 Conda 環境
RUN conda create -n llamaindex python=3.10 -y

# 設定環境變數，使 llamaindex 成為預設環境
ENV PATH /opt/conda/envs/llamaindex/bin:$PATH

# 安裝依賴
RUN pip install llama-index && \
    pip install llama-index-llms-ollama && \
    pip install llama-index-embeddings-huggingface

RUN mkdir /app
