FROM ubuntu:24.04

RUN apt update && \
    apt upgrade -y && \
    apt-get install -y pip python3 python3-pip mysql-client && \
    apt-get install -y pkg-config libmysqlclient-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 防止 Python 寫入 .pyc 文件
ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install llama-index --break-system-packages
RUN pip install llama-index-llms-ollama
RUN pip install llama_index.tools
RUN pip install llama-index-embeddings-huggingface

RUN mkdir app