FROM ubuntu:24.04

# 更新套件清單並安裝必要的工具
RUN apt-get update && \
    apt-get install -y \
    wget \
    bzip2 \
    ca-certificates \
    curl \
    git \
    build-essential \
    libmysqlclient-dev \
    python3-dev \
    mysql-client \
    pkg-config \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 下載並安裝 Miniconda
RUN wget -qO /tmp/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

# 設定環境變數
ENV PATH /opt/conda/bin:$PATH

# 初始化 Conda
RUN conda init

# 創建新的 Conda 環境
RUN conda create -n llamaindex python=3.10 -y

# 設定環境變數，使 llamaindex 成為預設環境
ENV PATH /opt/conda/envs/llamaindex/bin:$PATH
RUN echo "conda activate llamaindex" >> ~/.bashrc

# 安裝 llama-index 依賴
RUN pip install llama-index && \
    pip install llama-index-llms-ollama && \
    pip install llama-index-embeddings-huggingface

# 防止 Python 寫入 .pyc 文件
ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install 'Django==5.1'
RUN pip install 'tzdata==2024.1'
RUN pip install 'mysql-connector-python==9.0.0'
RUN pip install 'mysqlclient==2.1.1'
RUN pip install 'djangorestframework==3.15.2'
RUN pip install 'djangorestframework-simplejwt==5.3.1'
RUN pip install 'gunicorn==23.0.0' 'uvicorn==0.30.6'
RUN pip install 'django-asgi-lifespan==0.3.1'
RUN pip install 'django-redis==5.4.0'
RUN pip install 'django-cors-headers==4.4.0'
RUN pip install 'requests==2.32.3'
RUN pip install 'djangorestframework==3.15.2' 
RUN pip install 'djangorestframework-simplejwt==5.3.1'
RUN pip install 'google-auth==2.36.0'
RUN pip install 'pillow==11.0.0'
RUN pip install 'pytest' 'pytest-asyncio'

RUN mkdir /app